name: Deploy Fabric Workspace

on:
  push:
    branches:
      - taxi-data-dev  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install fabric-cicd
        run: |
          pip install fabric-cicd

     # - name: Deploy to Fabric
      #  run: |
       #   fabric-cicd deploy \
        #    --client-id ${{ secrets.FABRIC_CLIENT_ID }} \
         #   --client-secret ${{ secrets.FABRIC_CLIENT_SECRET }} \
          #  --tenant-id ${{ secrets.FABRIC_TENANT_ID }} \
          #  --workspace-id ${{ secrets.FABRIC_WORKSPACE_ID }} \
           # --folder ./workspace-artifacts

      - name: Mostrar nombres de los secrets (sin revelar valores)
        run: |
          echo "✅ FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}"
          echo "✅ FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}"
          echo "✅ FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}"
          echo "✅ FABRIC_WORKSPACE_ID: ${{ secrets.FABRIC_WORKSPACE_ID }}"
