name: Deploy Fabric Workspace

on:
  workflow_dispatch:
#  create:
#    branches:
#      - '*'  # Detecta la creación de cualquier rama
#  push:
#    branches:
#      - ws-taxi-data-dev    

permissions:
  contents: write  # NECESARIO para permitir el push

jobs:
  deploy-new-fabric-workspace:
    #if: github.ref != 'refs/heads/main'  # Evita ejecutar si es la rama main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install fabric-cicd
        run: |
          pip install fabric-cicd

      - name: Run Python ID update script
        run: python ./scripts/auth_spn_secret.py
        env:
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}
          FABRIC_WORKSPACE_ID: ${{ secrets.FABRIC_WORKSPACE_ID_MAIN }}
          FABRIC_TOKEN: ${{ secrets.FABRIC_TOKEN }}

      - name: Run Python commit in Fabric
        run: python ./scripts/fabric-api-git.py
        env:
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}
          FABRIC_WORKSPACE_ID: ${{ secrets.FABRIC_WORKSPACE_ID_MAIN }}
          FABRIC_TOKEN: ${{ secrets.FABRIC_TOKEN }}
          USER_GITHUB: $ {{ github.actor }}
          
#      - name: Commit and push updated object IDs
#        run: |
#          git config user.name "${{ github.actor }}"
#          git config user.email "${{ github.actor }}@users.noreply.github.com"
#          git add .
#          git diff-index --quiet HEAD || git commit -m "Actualizamos los IDS de los objetos después de crear la rama"
#          git remote set-url origin https://x-access-token:${{ secrets.FABRIC_GITHUB_TOKEN }}@github.com/Fran-Diaz-ENCA/taxi-data.git
#          git push

#         git commit -m "Actualizamos los IDS de los objetos después de crear la rama"

