name: Deploy Fabric Workspace

on:
  create:
    branches:
      - '*'  # Detecta la creación de cualquier rama
#  push:
#    branches:
#      - ws-taxi-data-dev    

jobs:
  deploy-new-fabric-workspace:
    if: github.ref != 'refs/heads/main'  # Evita ejecutar si es la rama main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install fabric-cicd
        run: |
          pip install fabric-cicd

      - name: Run Python ID update script
        run: python ./scripts/auth_spn_secret.py
        env:
          FABRIC_CLIENT_ID: ${{secrets.FABRIC_CLIENT_ID}}
          FABRIC_CLIENT_SECRET: ${{secrets.FABRIC_CLIENT_SECRET}}
          FABRIC_TENANT_ID: ${{secrets.FABRIC_TENANT_ID}}
          FABRIC_WORKSPACE_ID: ${{secrets.FABRIC_WORKSPACE_ID_MAIN}}
          
      - name: Commit and push updated object IDs
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Actualizamos los IDS de los objetos después de crear la rama"
          git push


#     - name: Mostrar nombres de los secrets (sin revelar valores)
#        run: |
#          echo "✅ FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}"
#          echo "✅ FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}"
#          echo "✅ FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}"
#          echo "✅ FABRIC_WORKSPACE_ID: ${{ secrets.FABRIC_WORKSPACE_ID }}"
